### ISSUE TITLE
Undefined symbol error adding Spek with SPM 

### ISSUE THREAD

**Issue by eduhcano** [onmyway133/Spek#1]
Hi after adding Spek with SPM in a clean project with Xcode 12.4 I get this error in Build time:

Undefined symbol: _OBJC_METACLASS_$_XCTestCase

![Captura de pantalla 2021-04-09 a las 20 10 02](https://user-images.githubusercontent.com/47054/114223116-bad6f000-996f-11eb-90bf-605bb72765e9.png)

Is there anything else that I must do to make it compile? thanks.

**Comment by onmyway133** [comment]
@eduhcano Hi, Spek works only with a Test target, not App target. Can you check that you 're embedding Spek for Test target only?

**Comment by eduhcano** [comment]
Yes, that was my issue, I've embedded it for my Test target, and works perfect, many thanks 🙏🏼.
